name: CI/CD Pipeline

permissions:
  contents: write
  packages: write

on:
  push:
    branches: [ "dev", "staging" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push microservice1 Docker image
        run: |
          VERSION=sit-latest
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            VERSION=dev-latest
          fi
          
          echo "Building microservice1 image with version: $VERSION"
          
          cd microservice1
          docker build -t ghcr.io/${{ github.repository }}/microservice1:$VERSION .
          docker push ghcr.io/${{ github.repository }}/microservice1:$VERSION
          
          # 返回仓库根目录
          cd ..
          
          # 检查文件是否存在
          if [ ! -f environments/dev/microservice1-values.yaml ]; then
            echo "Error: environments/dev/microservice1-values.yaml not found"
            exit 1
          fi
          if [ ! -f environments/staging/microservice1-values.yaml ]; then
            echo "Error: environments/staging/microservice1-values.yaml not found"
            exit 1
          fi
          
          # 更新 Helm 值文件中的 tag
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          sed -i "s|tag: .*|tag: \"$VERSION\"|" environments/dev/microservice1-values.yaml
          sed -i "s|tag: .*|tag: \"$VERSION\"|" environments/staging/microservice1-values.yaml
          
          # 提交更新
          git add environments/dev/microservice1-values.yaml
          git add environments/staging/microservice1-values.yaml
          git commit -m "chore: Update microservice1 image tags to $VERSION [skip ci]" || true
          git push

      - name: Build and push microservice2 Docker image
        run: |
          VERSION=sit-latest
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            VERSION=dev-latest
          fi
          
          echo "Building microservice2 image with version: $VERSION"
          
          cd microservice2
          docker build -t ghcr.io/${{ github.repository }}/microservice2:$VERSION .
          docker push ghcr.io/${{ github.repository }}/microservice2:$VERSION
          
          # 返回仓库根目录
          cd ..
          
          # 检查文件是否存在
          if [ ! -f environments/dev/microservice2-values.yaml ]; then
            echo "Error: environments/dev/microservice2-values.yaml not found"
            exit 1
          fi
          if [ ! -f environments/staging/microservice2-values.yaml ]; then
            echo "Error: environments/staging/microservice2-values.yaml not found"
            exit 1
          fi
          
          # 更新 Helm 值文件中的 tag
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          sed -i "s|tag: .*|tag: \"$VERSION\"|" environments/dev/microservice2-values.yaml
          sed -i "s|tag: .*|tag: \"$VERSION\"|" environments/staging/microservice2-values.yaml
          
          # 提交更新
          git add environments/dev/microservice2-values.yaml
          git add environments/staging/microservice2-values.yaml
          git commit -m "chore: Update microservice2 image tags to $VERSION [skip ci]" || true
          git push
