name: CI/CD Pipeline for Microservices (GHCR)

on:
  push:
    branches:
      - dev
      - staging

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push microservice1 Docker image
        run: |
          TAG=""
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            TAG="dev-latest"
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            TAG="sit-latest"
          fi
          
          cd microservice1
          mvn clean package -DskipTests
          docker build -t ghcr.io/${{ github.repository }}/microservice1:$TAG .
          docker push ghcr.io/${{ github.repository }}/microservice1:$TAG
          cd ..
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin ${{ github.ref_name }} --rebase
          
          sed -i "s|tag: \".*\"|tag: \"$TAG\"|g" "environments/${{ github.ref_name }}/microservice1-values.yaml"
          git add "environments/${{ github.ref_name }}/microservice1-values.yaml"
          git commit -m "Update microservice1 image tag to $TAG [skip ci]"
          git push

      - name: Build and push microservice2 Docker image
        run: |
          TAG=""
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            TAG="dev-latest"
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            TAG="sit-latest"
          fi
          
          cd microservice2
          mvn clean package -DskipTests
          docker build -t ghcr.io/${{ github.repository }}/microservice2:$TAG .
          docker push ghcr.io/${{ github.repository }}/microservice2:$TAG
          cd ..
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin ${{ github.ref_name }} --rebase
          
          sed -i "s|tag: \".*\"|tag: \"$TAG\"|g" "environments/${{ github.ref_name }}/microservice2-values.yaml"
          git add "environments/${{ github.ref_name }}/microservice2-values.yaml"
          git commit -m "Update microservice2 image tag to $TAG [skip ci]"
          git push
