# 修正了CI/CD Pipeline的GitOps部署逻辑

name: CI/CD Pipeline

# 新增权限配置，确保可以推送到 GHCR
permissions:
  contents: write
  packages: write

on:
  push:
    branches: [ "dev", "staging" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push microservice1 Docker image
        run: |
          VERSION=sit-latest
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            VERSION=dev-latest
          fi
          
          echo "Building microservice1 image with version: $VERSION"
          
          cd microservice1
          docker build -t ghcr.io/${{ github.repository }}/microservice1:$VERSION .
          docker push ghcr.io/${{ github.repository }}/microservice1:$VERSION
          
          # 更新 Helm chart values，并提交到 Git
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # 修复 sed 命令的路径，以确保 ArgoCD 能找到 values 文件
          sed -i "s|image: .*\$|image: ghcr.io/${{ github.repository }}/microservice1:$VERSION|" charts/microservice1/environments/dev/microservice1-values.yaml
          sed -i "s|image: .*\$|image: ghcr.io/${{ github.repository }}/microservice1:$VERSION|" charts/microservice1/environments/staging/microservice1-values.yaml

          # 在 CI/CD 流程中提交更新
          git add charts/microservice1/environments/dev/microservice1-values.yaml
          git add charts/microservice1/environments/staging/microservice1-values.yaml
          git commit -m "chore: Update microservice1 image tags to $VERSION [skip ci]" || true
          git push

      - name: Build and push microservice2 Docker image
        run: |
          VERSION=sit-latest
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            VERSION=dev-latest
          fi
          
          echo "Building microservice2 image with version: $VERSION"
          
          cd microservice2
          docker build -t ghcr.io/${{ github.repository }}/microservice2:$VERSION .
          docker push ghcr.io/${{ github.repository }}/microservice2:$VERSION
          
          # 更新 Helm chart values，并提交到 Git
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # 修复 sed 命令的路径，以确保 ArgoCD 能找到 values 文件
          sed -i "s|image: .*\$|image: ghcr.io/${{ github.repository }}/microservice2:$VERSION|" charts/microservice2/environments/dev/microservice2-values.yaml
          sed -i "s|image: .*\$|image: ghcr.io/${{ github.repository }}/microservice2:$VERSION|" charts/microservice2/environments/staging/microservice2-values.yaml
          
          # 在 CI/CD 流程中提交更新
          git add charts/microservice2/environments/dev/microservice2-values.yaml
          git add charts/microservice2/environments/staging/microservice2-values.yaml
          git commit -m "chore: Update microservice2 image tags to $VERSION [skip ci]" || true
          git push
