image:
  repository: ghcr.io/1979447992/gitops-demo/microservice2
  tag: "dev-0726a3e"
  pullPolicy: Always

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "traefik"
  hosts:
    - host: microservice2.local
      paths:
        - path: /
          pathType: Prefix
